# Generated by Django 5.1.15 on 2026-02-07 20:30

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('version', models.CharField(default='1.0.0', max_length=32)),
                ('schema', models.JSONField(default=dict, help_text='JSON Schema for validation')),
                ('uischema', models.JSONField(blank=True, default=dict, help_text='UI Schema for form rendering')),
                ('defaults', models.JSONField(blank=True, default=dict, help_text='Default values template')),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_profiles', to='records.profile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jsonld', models.JSONField(default=dict, help_text='Complete JSON-LD document')),
                ('title', models.TextField(blank=True, default='', help_text='Extracted from schema:name')),
                ('creators', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, help_text='Extracted from schema:creator', size=None)),
                ('identifier', models.TextField(db_index=True, help_text='DOI or UUID identifier', unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='records.profile')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['jsonld'], name='record_jsonld_gin')],
            },
        ),
    ]
