# Generated by Django 5.1.15 on 2026-02-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnownOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True)),
                ('identifier_type', models.TextField(blank=True, default='')),
                ('identifier_value', models.TextField(blank=True, default='')),
                ('identifier_url', models.TextField(blank=True, default='')),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'identifier_value'), name='unique_org_name_id')],
            },
        ),
        migrations.CreateModel(
            name='KnownPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True)),
                ('identifier_type', models.TextField(blank=True, default='')),
                ('identifier_value', models.TextField(blank=True, default='')),
                ('identifier_url', models.TextField(blank=True, default='')),
                ('affiliation_name', models.TextField(blank=True, default='')),
                ('affiliation_identifier_type', models.TextField(blank=True, default='')),
                ('affiliation_identifier_value', models.TextField(blank=True, default='')),
                ('affiliation_identifier_url', models.TextField(blank=True, default='')),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'identifier_value'), name='unique_person_name_id')],
            },
        ),
    ]
