# Generated by Django 5.1.15 on 2026-02-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_knownorganization_knownperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('deprecated', 'Deprecated')], default='draft', max_length=16),
        ),
    ]
