# Generated by Django 5.1.15 on 2026-02-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ada_bridge', '0002_bundlesession'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdaJsonTable',
            fields=[
                ('doi', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('jsonobject', models.JSONField()),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'json_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdaRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, null=True)),
                ('submission_type', models.CharField(max_length=100)),
                ('general_type', models.CharField(max_length=100)),
                ('specific_type', models.CharField(blank=True, max_length=100, null=True)),
                ('doi', models.CharField(blank=True, max_length=100, null=True)),
                ('process_status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'records',
                'managed': False,
            },
        ),
    ]
